"""empty message

Revision ID: 10e4d4c0c95c
Revises: da15aec5b7c3
Create Date: 2022-12-03 18:55:38.606392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e4d4c0c95c'
down_revision = 'da15aec5b7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
