"""empty message

Revision ID: 179ffaf28bdc
Revises: 6badd7d06b6c
Create Date: 2022-12-02 18:17:41.171705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179ffaf28bdc'
down_revision = '6badd7d06b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
