"""empty message

Revision ID: 91abc31bf1de
Revises: e52cf9b47e2f
Create Date: 2022-12-04 02:54:37.372417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "91abc31bf1de"
down_revision = "e52cf9b47e2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.REAL(),
            type_=sa.Float(precision=2),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Float(precision=2),
            type_=sa.REAL(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
